version: "3"

services:
    nginx:
        build: ./nginx
        container_name: nginx
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports: 
            - 8080:8080
        restart: always
        env_file:
            - .env
