version: "3"

services:
    nginx:
        build: ./nginx
        container_name: nginx
        ports: 
            - 8080:8080
        links:
            - application
        restart: always
        env_file:
            - .env

    mongodb:
        image: mongo
        container_name: mongodb
        ports: 
          - 27017:27017
        restart: always
        env_file:
            - .env

    application:
        build: ./application
        container_name: application
        links:
          - mongodb
        restart: always
        env_file:
            - .env

